spring.application.name=backend
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-plain-lab-a43ecmoa-pooler.us-east-1.aws.neon.tech/quiz-app-db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zZsxm7AcSPX9
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Ignore exceptions if db is not connected yet, allow app to start for testing
# (spring.datasource.continue-on-error=true)
